FROM golang:1.6.3
MAINTAINER rivine.io

ENV CGO_ENABLED 0
COPY . /go/src/github.com/rivine/rivine
WORKDIR /go/src/github.com/rivine/rivine

EXPOSE 23110 23112

RUN go install -v -tags 'debug dev profile' ./... 
ENTRYPOINT rivined --no-bootstrap